### ISSUE TITLE
adding program to find the largest sum subarray in a given array

### ISSUE THREAD

**Issue by Divyammmmmm** [Divyammmmmm/hacktoberfest#10]

**Comment by sid172014** [comment]
Hey , can you please assign this to me ? I would love to work on this..

**Comment by Aishika3** [comment]
I want to work on this

**Comment by ishatri** [comment]
Would love to work on this issue

**Comment by asv02** [comment]
@Divyammmmmm ,I can add a very well-explained code for this question, please assign it to me under hacktoberfest label.

**Comment by robert1745** [comment]
assign me @Divyammmmmm  i will give the best solution

**Comment by robert1745** [comment]
assign me @Divyammmmmm  i will give the best solution
